CREATE CONSTRAINT contact_list_name_constraint IF NOT EXISTS FOR (c:ContactList) REQUIRE c.name IS UNIQUE;
CREATE CONSTRAINT datasource_name_constraint IF NOT EXISTS FOR (d:DataSource) REQUIRE d.name IS UNIQUE;
CREATE INDEX ix_job_id IF NOT EXISTS FOR (jb:Job) ON (jb.id);
CREATE INDEX ix_contactlist_id IF NOT EXISTS FOR (cl:ContactList) ON (cl.id);
CREATE INDEX ix_contact_Id_New IF NOT EXISTS FOR (c:Contact) ON (c.Id);
CREATE INDEX ix_attribute_type IF NOT EXISTS FOR (m:Attribute) on (m.type);
CREATE INDEX ix_emptyjob_id IF NOT EXISTS FOR (m:EmptyJob) on (m.id);
CREATE INDEX ix_deletedcontactlist_id IF NOT EXISTS FOR (m:DeletedContactList) on (m.id);
CREATE INDEX ix_attribute_name IF NOT EXISTS FOR (m:Attribute) ON (m.name);
CREATE INDEX ix_attribute_id IF NOT EXISTS FOR (m:Attribute) ON (m.id);